---
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 300MiB
    minimumSize: 32MiB
    label: "EFI"
userSwapChoices:
    - none
initialSwapChoice: none
drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: alongside
defaultFileSystemType: "btrfs"
availableFileSystemTypes: ["btrfs"]
enableLuksAutomatedPartitioning: true
partitionLayout:
    - name: "rocketos"
      filesystem: btrfs
      mountPoint: "/"
      size: 100%
