---
units:
    - name: NetworkManager.service
      action: enable
      mandatory: true
    - name: bluetooth.service
      action: enable
    - name: sddm.service
      action: enable
      mandatory: true
    - name: fstrim.timer
      action: enable
    - name: snapper-timeline.timer
      action: enable
    - name: snapper-cleanup.timer
      action: enable
    - name: grub-btrfsd.service
      action: enable
