---
defaultGroups:
    - wheel
    - video
    - audio
    - input
    - name: games
      must_exist: false
      system: true
autologinGroup: autologin
doAutologin: true
sudoersGroup: wheel
sudoersConfigureWithGroup: true
setRootPassword: false
doReusePassword: false
passwordRequirements:
    minLength: 4
    maxLength: -1
allowWeakPasswords: false
user:
    shell: /bin/bash
    forbidden_names: [ root, rocket ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "rocket-${cpu}"
