---
showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
    requiredStorage: 40
    requiredRam: 4.0
    internetCheckUrl: https://archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
