# Rocket OS Calamares settings
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id: rocket-post
  module: shellprocess
  config: shellprocess-rocket-post.conf
- id: rocket-grub
  module: shellprocess
  config: shellprocess-rocket-grub.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - shellprocess@rocket-post
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - initcpio
  - bootloader
  - shellprocess@rocket-grub
  - umount
- show:
  - finished

branding: rocket
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
